In [1]:
import cv2
import numpy as np
print(cv2.__version__)


4.11.0


In [2]:
image = np.zeros((200, 400), np.uint8)

image[:] = 200
image

array([[200, 200, 200, ..., 200, 200, 200],
       [200, 200, 200, ..., 200, 200, 200],
       [200, 200, 200, ..., 200, 200, 200],
       ...,
       [200, 200, 200, ..., 200, 200, 200],
       [200, 200, 200, ..., 200, 200, 200],
       [200, 200, 200, ..., 200, 200, 200]], dtype=uint8)

In [3]:
title1, title2 = "position1", "position2"

cv2.namedWindow(title1, flags=cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title2, flags=cv2.WINDOW_NORMAL)

In [4]:
cv2.moveWindow(title1, 150, 150)
cv2.moveWindow(title2, 400, 50)

In [5]:
cv2.imshow(title1, image)
cv2.imshow(title2, image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.imshow(title1, image)
cv2.imshow(title2, image)

cv2.resizeWindow(title1, 400, 300)
cv2.resizeWindow(title2, 400, 300)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
switch_case = {
    ord('a'): "a키 입력",
    ord('b'): "b키 입력",
    0x41: "A키 입력",
    int('0x42', 16): "B키 입력",
    2424832: "왼쪽 화살표키 입력",
    2490368: "윗쪽 화살표키 입력",
    2555904: "오른쪽 화살표키 입력",
    2621440: "아래쪽 화살표키 입력"
}

In [16]:
image = np.ones((200,300), np.float32)
cv2.namedWindow("Keyboard Event")
cv2.imshow("Keyboard Event", image)

while True:
    key = cv2.waitKey(100)
    if key == 27: break
        
    try:
        result = switch_case[key]
        print(result)
    
    except KeyError:
        result = -1
        
cv2.destroyAllWindows()

a키 입력
a키 입력
b키 입력
A키 입력
A키 입력


KeyboardInterrupt: 

In [11]:
def onMouse(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print("마우스 왼쪽 버튼 누르기")
    elif event == cv2.EVENT_RBUTTONDOWN:
        print("마우스 오른쪽 버튼 누르기")
    elif event == cv2.EVENT_RBUTTONUP:
        print("마우스 오른쪽 버튼 떼기")
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        print("마우스 왼쪽 버튼 더블클릭")

In [12]:
image = np.full((200, 300), 255, np.uint8)

title1, title2 = "Mouse Event1", "Mouse Event2"

cv2.imshow(title1, image)
cv2.imshow(title2, image)

cv2.setMouseCallback(title1, onMouse)

cv2.waitKey(0)
cv2.destroyAllWindows()

마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 오른쪽 버튼 누르기
마우스 오른쪽 버튼 떼기


In [17]:
def onChange(value):
    global image, title
    add_value = value - int(image[0][0])
    print("추가 화소값: ", add_value)
    image[:] = image + add_value
    cv2.imshow(title, image)

In [18]:
image = np.zeros((400, 600), np.uint8)

title = "Trackbar Event"
cv2.imshow(title, image)

cv2.createTrackbar("Brighteness", title, image[0][0], 255, onChange)

cv2.waitKey(0)
cv2.destroyAllWindows

추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  3
추가 화소값:  2
추가 화소값:  2
추가 화소값:  2
추가 화소값:  1
추가 화소값:  2
추가 화소값:  2
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  2
추가 화소값:  1
추가 화소값:  2
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  1
추가 화소값:  2
추가 화소값:  1
추가 화소값:  2

<function destroyAllWindows>

In [19]:
blue, green, red = (255, 0 ,0), (0, 255, 0), (0, 0, 255)
image = np.zeros((400, 600, 3), np.uint8)
image[:] = (255, 255, 255)

pt1, pt2 = (50, 50), (250, 150)
pt3, pt4 = (400, 150), (500, 50)
roi = (50, 200, 200 ,100)

cv2.line(image, pt1, pt2, red)
cv2.line(image, pt3, pt4, green, 3, cv2.LINE_AA)

cv2.rectangle(image, pt1, pt2, blue, 3, cv2.LINE_4)
cv2.rectangle(image, roi, red, 3, cv2.LINE_8)
cv2.rectangle(image, (400, 200, 100, 100), green, cv2.FILLED)

cv2.imshow("Line & Rectangle", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
olive, violet, brown = (128, 128, 0), (221, 160, 221), (42, 42, 165)
pt1, pt2 = (50, 230), (50, 310)

image = np.zeros((350, 500, 3), np.uint8)
image.fill(255)

cv2.putText(image, 'SIMPLEX', (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, brown)
cv2.putText(image, 'DUPLEX', (50, 130), cv2.FONT_HERSHEY_DUPLEX, 3, olive)
cv2.putText(image, 'TRIPLEX', pt1, cv2.FONT_HERSHEY_TRIPLEX, 2, violet)
fontFace = cv2.FONT_HERSHEY_PLAIN | cv2.FONT_ITALIC
cv2.putText(image, 'ITALIC', pt2, fontFace, 4, violet)

cv2.imshow('Put Text', image)
cv2.waitKey(0)

In [ ]:
#04.09 챕터5. Open CV 및 사용자 인터페이스 2

In [4]:
def print_matInfo(name, image):
    if image.dtype == 'uint8': mat_type = 'CV_8U'
    elif image.dtype == 'int8': mat_type = 'CV_8S'
    elif image.dtype == 'uint16': mat_type = 'CV16U'
    elif image.dtype == 'int16': mat_type = 'CV16S'
    elif image.dtype == 'float32': mat_type = 'CV32F'
    elif image.dtype == 'float64': mat_type = 'CV64F'
        
    nchannel = 3 if image.ndim == 3 else 1
    
    ## depth, channel 출력
    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)" % (name, image.dtype, nchannel, mat_type, nchannel))

In [5]:
title1, title2 = 'gray2gray', 'gray2color'
gray2gray = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_gray.jpg", cv2.IMREAD_GRAYSCALE)
gray2color = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_color.jpg", cv2.IMREAD_COLOR)

print_matInfo(title1, gray2gray)
print_matInfo(title2, gray2color)

   gray2gray: depth(uint8), channels(1) -> mat_type(CV_8UC1)
  gray2color: depth(uint8), channels(3) -> mat_type(CV_8UC3)


In [ ]:
if gray2gray is None or gray2color is None:
    raise Exception("영상 파일 읽기 에러")
    
# 행렬 좌표 (100, 100) 화소 값 출력
print("행렬 좌표 (100, 100) 화소 값")
print("%s %s" % (title1, gray2gray[100, 100]))
print("%s %s\n" % (title2, gray2color[100, 100]))

cv2.imshow(title1, gray2gray)
cv2.imshow(title2, gray2color)
cv2.waitKey(0)
cv2.destroyAllWindows()

행렬 좌표 (100, 100) 화소 값
gray2gray 106
gray2color [197 145  98]



In [ ]:
import cv2
import numpy as np

def print_matInfo(name, image):
    if image is None:
        print(f"[오류] {name} 이미지를 읽을 수 없습니다.")
        return

    if image.dtype == np.uint8: mat_type = 'CV_8U'
    elif image.dtype == np.int8: mat_type = 'CV_8S'
    elif image.dtype == np.uint16: mat_type = 'CV16U'
    elif image.dtype == np.int16: mat_type = 'CV16S'
    elif image.dtype == np.float32: mat_type = 'CV32F'
    elif image.dtype == np.float64: mat_type = 'CV64F'
    else: mat_type = 'Unknown'

    nchannel = 3 if image.ndim == 3 else 1

    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)" %
          (name, image.dtype, nchannel, mat_type, nchannel))

# --- 이미지 읽기
title1, title2 = '16bit unchanged', '32bit unchanged'
color2unchanged1 = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_16.tif", cv2.IMREAD_UNCHANGED)
color2unchanged2 = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_32.tif", cv2.IMREAD_UNCHANGED)

# --- 예외 처리
if color2unchanged1 is None or color2unchanged2 is None:
    raise Exception("영상 파일 읽기 에러")

# --- 화소값 출력
print("16/32비트 영상 행렬 좌표(10, 10) 화소 값")
print(title1, "원소 자료형: ", type(color2unchanged1[10][10][0]))
print(title1, "화소값(3원소): ", color2unchanged1[10, 10])
print(title2, "원소 자료형: ", type(color2unchanged2[10][10][0]))
print(title2, "화소값(3원소): ", color2unchanged2[10, 10])
print()

# --- 이미지 정보 출력
print_matInfo(title1, color2unchanged1)
print_matInfo(title2, color2unchanged2)

# --- 이미지 표시
cv2.imshow(title1, color2unchanged1.astype('uint8'))  # 16비트를 8비트로 보기 좋게 변환
cv2.imshow(title2, (color2unchanged2 * 255).astype('uint8'))  # 32비트 float → 8비트로 스케일링
cv2.waitKey(0)
cv2.destroyAllWindows()

16/32비트 영상 행렬 좌표(10, 10) 화소 값
16bit unchanged 원소 자료형:  <class 'numpy.uint16'>
16bit unchanged 화소값(3원소):  [48573 34438 23387]
32bit unchanged 원소 자료형:  <class 'numpy.float32'>
32bit unchanged 화소값(3원소):  [0.7456989  0.52237624 0.36376417]

16bit unchanged: depth(uint16), channels(3) -> mat_type(CV16UC3)
32bit unchanged: depth(float32), channels(3) -> mat_type(CV32FC3)


In [2]:
image = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_color.jpg", cv2.IMREAD_COLOR)
if image is None:
    raise Exception("영상 파일 읽기 에러")
    
params_jpg = (cv2.IMWRITE_JPEG_QUALITY, 10)
params_png = [cv2.IMWRITE_PNG_COMPRESSION, 9]

cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test1.jpg", image)
cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test2.jpg", image, params_jpg)
cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test3.jpg", image, params_png)
cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test4.bmp", image)

print("저장 완료")

저장 완료


In [ ]:
import cv2
import numpy as np

image8 = cv2.imread("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/read_color.jpg", cv2.IMREAD_COLOR)
if image8 is None:
    raise Exception("영상 파일 읽기 에러")

image16 = np.uint16(image8 * (65535 / 255))
image32 = np.float32(image8 / 255.0)  # ✅ float32로 수정

print("image8 행렬의 일부\n", image8[10:12, 10:13])
print("image16 행렬의 일부\n", image16[10:12, 10:13])
print("image32 행렬의 일부\n", image32[10:12, 10:13])

# 저장 (float32는 직접 저장 안됨 → 8비트로 변환 후 저장)
cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test_16.tif", image16)
cv2.imwrite("C:/Users/SAMSUNG/Desktop/Pattern_Recognition_Class/images2/write_test_32.tif", (image32 * 255).astype('uint8'))

# 표시
cv2.imshow("image16", image16.astype('uint8'))  # 보기용
cv2.imshow("image32", (image32 * 255).astype('uint8'))
cv2.waitKey(0)
cv2.destroyAllWindows()


image8 행렬의 일부
 [[[189 134  91]
  [189 134  91]
  [189 134  91]]

 [[189 134  91]
  [189 134  91]
  [189 134  91]]]
image16 행렬의 일부
 [[[48573 34438 23387]
  [48573 34438 23387]
  [48573 34438 23387]]

 [[48573 34438 23387]
  [48573 34438 23387]
  [48573 34438 23387]]]
image32 행렬의 일부
 [[[0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]]

 [[0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]]]


In [4]:
import cv2

def put_string(frame, text, pt, value, color = (0, 0, 255)):
    text += str(value)
    shade = (pt[0] + 2, pt[1] + 2)
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(frame, text, shade, font, 0.7, (0, 0, 0), 2)
    cv2.putText(frame, text, pt, font, 0.7, color, 2)
    
capture = cv2.VideoCapture(0)
if capture.isOpened() == False:
    raise Exception("카메라 연결 안 됨.")
    
print("너비 %d" % capture.get(cv2.CAP_PROP_FRAME_WIDTH))
print("높이 %d" % capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
print("노출 %f" % capture.get(cv2.CAP_PROP_EXPOSURE))
print("밝기 %f" % capture.get(cv2.CAP_PROP_BRIGHTNESS))

너비 640
높이 480
노출 -6.000000
밝기 64.000000


In [5]:
while True:
    ret, frame = capture.read()
    if not ret:
        break
    if cv2.waitKey(30) >= 0:
        break
    
    exposure = capture.get(cv2.CAP_PROP_EXPOSURE)
    put_string(frame, 'EXPOS: ', (10, 40), exposure)
    
    title = "View Frame from Camera"
    cv2.imshow(title, frame)
    
capture.release()
cv2.destroyAllWindows()

In [2]:
import cv2

def put_string(frame, text, pt, value, color = (0, 0, 255)):
    text += str(value)
    shade = (pt[0] + 2, pt[1] + 2)
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(frame, text, shade, font, 0.7, (0, 0, 0), 2)
    cv2.putText(frame, text, pt, font, 0.7, color, 2)
    
def zoom_bar(value):
    global capture
    capture.set(cv2.CAP_PROP_ZOOM, value) # 줌 설정

def focus_bar(value):
    global capture
    capture.set(cv2.CAP_PROP_FOCUS, value)
    
capture = cv2.VideoCapture(0)
if capture.isOpened() == False:
    raise Exception("카메라 연결 안 됨.")

In [3]:
title = "Change Camera Properties"
cv2.namedWindow(title)
cv2.createTrackbar('zoom', title, 0, 10, zoom_bar)
cv2.createTrackbar('focus', title, 0, 40, focus_bar)

while True:
    ret, frame = capture.read()
    if not ret:
        break
    if cv2.waitKey(30) >= 0:
        break
        
    zoom = int(capture.get(cv2.CAP_PROP_ZOOM))
    focus = int(capture.get(cv2.CAP_PROP_FOCUS))
    
    put_string(frame, 'zoom : ', (10, 240), zoom)
    put_string(frame, 'focus : ', (10, 270), focus)
    
    cv2.imshow(title, frame)

capture.release()
cv2.destroyAllWindows()